# Generated by Django 5.1.7 on 2026-07-14 09:14

import django.db.models.deletion
import party.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=party.models.generate_party_code, editable=False, max_length=12, unique=True)),
                ('mode', models.CharField(choices=[('food_delivery', 'Food Delivery'), ('dineout', 'Dineout')], max_length=15)),
                ('strategy', models.CharField(blank=True, choices=[('member', 'Member-wise'), ('whole', 'Whole Party')], max_length=10, null=True)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('budget', models.PositiveIntegerField()),
                ('expected_guest_count', models.PositiveIntegerField()),
                ('veg_count', models.PositiveIntegerField(default=0)),
                ('non_veg_count', models.PositiveIntegerField(default=0)),
                ('jain_count', models.PositiveIntegerField(default=0)),
                ('vegan_count', models.PositiveIntegerField(default=0)),
                ('diabetic_count', models.PositiveIntegerField(default=0)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('party_start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('dietary_pref', models.CharField(choices=[('any', 'Any'), ('veg', 'Veg'), ('non_veg', 'Non-Veg'), ('vegan', 'Vegan'), ('jain', 'Jain'), ('diabetic', 'Diabetic')], default='any', max_length=10)),
                ('is_late', models.BooleanField(default=False)),
                ('late_offset_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='party.party')),
            ],
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='party.guest')),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='party_guest_token_h_3bc892_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['code'], name='party_party_code_a53fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['party', 'name'], name='party_guest_party_i_348037_idx'),
        ),
    ]
