# Generated by Django 5.1.7 on 2026-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_swiggyusercredential_swiggyoauthattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiggyoauthattempt',
            name='code_verifier_hash',
        ),
        migrations.AddField(
            model_name='swiggyoauthattempt',
            name='code_verifier_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='swiggyusercredential',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
    ]
