# Generated by Django 5.1.7 on 2026-07-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=150)),
                ('seating_capacity_required', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('special_request', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='party.party')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_by', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=10)),
                ('last_modified_by', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=10)),
                ('restaurant_id', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('item_total', models.PositiveIntegerField(default=0)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('taxes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('fired', 'Fired'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('fire_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='party.guest')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='party.party')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_jain_compatible', models.BooleanField(default=False)),
                ('is_diabetic_friendly', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['party', 'status'], name='order_order_party_i_1fb26a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fire_time'], name='order_order_fire_ti_94159f_idx'),
        ),
    ]
