<<<<<<< HEAD
# Generated by Django 5.1.7 on 2026-07-14 09:14
=======
# Generated by Django 5.1.7 on 2026-07-20 11:05
>>>>>>> 8475573 (chore(migrations): reset and regenerate all migrations for Supabase)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('restaurant_filter', 'Restaurant Filter (Food Delivery)'), ('whole_sum_optimizer', 'Whole-Sum Quantity Optimizer'), ('dineout_ranking', 'Dineout Restaurant Ranking'), ('scheduling', 'Late-Arrival Scheduling Suggestion'), ('merge_check', 'Order Merge Detection'), ('budget_guardian', 'Budget Guardian'), ('budget_check', 'Budget Guardian Check')], max_length=25)),
                ('prompt_template_version', models.CharField(default='v1', max_length=20)),
                ('request_payload', models.JSONField()),
                ('response_raw', models.TextField(blank=True)),
                ('response_parsed', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groq_calls', to='party.party')),
            ],
            options={
                'indexes': [models.Index(fields=['call_type', 'created_at'], name='core_groqca_call_ty_963987_idx'), models.Index(fields=['party', 'created_at'], name='core_groqca_party_i_3cf7e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=10)),
                ('notification_type', models.CharField(choices=[('order_edited_by_host', 'Order Edited by Host'), ('guest_order_placed', 'Guest Order Placed'), ('merge_detected', 'Order Merge Detected'), ('budget_warning', 'Budget Warning'), ('late_order_fired', 'Late Order Auto-Fired'), ('booking_confirmed', 'Dineout Booking Confirmed')], max_length=25)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='party.party')),
                ('recipient_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='party.guest')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['party', 'is_read'], name='core_notifi_party_i_c334b1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipient_guest__isnull', True), ('recipient_type', 'host'), ('recipient_user__isnull', False)), models.Q(('recipient_guest__isnull', False), ('recipient_type', 'guest'), ('recipient_user__isnull', True)), _connector='OR'), name='notification_recipient_matches_type')],
            },
        ),
    ]
